name: Build
on:
  push:
    branches:
    - main
    - '*'
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.406

    - name: Clean
      run: dotnet clean ./OutOfSchool/OutOfSchool.sln --configuration Release && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore ./OutOfSchool/

    - name: Build
      run: dotnet build --configuration Release --no-restore ./OutOfSchool

    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release ./OutOfSchool
